module.exports = [
	{ code: 780, name: 'ALİAĞA' },
	{ code: 751, name: 'ALSANCAK' },
	{ code: 752, name: 'ALSANCAK-BASMANE' },
	{ code: 579, name: 'ALTINDAĞ' },
	{ code: 580, name: 'ATATÜRK-OSMANGAZİ' },
	{ code: 782, name: 'AYRANCILAR' },
	{ code: 581, name: 'BALÇOVA' },
	{ code: 582, name: 'BASIN SİTESİ' },
	{ code: 783, name: 'BAYINDIR' },
	{ code: 583, name: 'BAYRAKLI' },
	{ code: 784, name: 'BERGAMA' },
	{ code: 785, name: 'BEYDAĞ' },
	{ code: 584, name: 'BORNOVA 1' },
	{ code: 585, name: 'BORNOVA 2' },
	{ code: 586, name: 'BORNOVA 3' },
	{ code: 587, name: 'BOZYAKA' },
	{ code: 588, name: 'BUCA 1' },
	{ code: 589, name: 'BUCA 2' },
	{ code: 578, name: 'ÇAMDİBİ' },
	{ code: 1455, name: 'ÇANDARLI' },
	{ code: 787, name: 'ÇEŞME' },
	{ code: 591, name: 'ÇİĞLİ' },
	{ code: 788, name: 'DİKİLİ' },
	{ code: 789, name: 'ESKİ FOÇA' },
	{ code: 592, name: 'ESKİİZMİR-CENNETÇEŞME' },
	{ code: 593, name: 'EŞREFPAŞA' },
	{ code: 595, name: 'EVKA 1' },
	{ code: 596, name: 'GAZİEMİR' },
	{ code: 597, name: 'GEDİZ' },
	{ code: 688, name: 'GÜLTEPE' },
	{ code: 1454, name: 'GÜMÜLDÜR-ÖZDERE' },
	{ code: 750, name: 'GÜMÜŞPALA' },
	{ code: 753, name: 'GÜZELBAHÇE' },
	{ code: 754, name: 'HATAY' },
	{ code: 755, name: 'İNCİRALTI' },
	{ code: 756, name: 'KARABAĞLAR' },
	{ code: 790, name: 'KARABURUN' },
	{ code: 757, name: 'KARŞIYAKA 1' },
	{ code: 768, name: 'KARŞIYAKA 2' },
	{ code: 769, name: 'KARŞIYAKA 3' },
	{ code: 770, name: 'KARŞIYAKA 4' },
	{ code: 791, name: 'KEMALPAŞA' },
	{ code: 792, name: 'KINIK' },
	{ code: 793, name: 'KİRAZ' },
	{ code: 794, name: 'MENDERES' },
	{ code: 795, name: 'MENEMEN' },
	{ code: 772, name: 'MİTHATPAŞA' },
	{ code: 796, name: 'MORDOĞAN' },
	{ code: 773, name: 'NARLIDERE' },
	{ code: 797, name: 'ÖDEMİŞ' },
	{ code: 774, name: 'PINARBAŞI' },
	{ code: 775, name: 'SARNIÇ' },
	{ code: 799, name: 'SEFERİHİSAR' },
	{ code: 800, name: 'SELÇUK' },
	{ code: 776, name: 'ŞİRİNYER' },
	{ code: 802, name: 'TİRE' },
	{ code: 803, name: 'TORBALI' },
	{ code: 801, name: 'URLA' },
	{ code: 777, name: 'ÜÇYOL' },
	{ code: 804, name: 'YENİ FOÇA' },
	{ code: 805, name: 'YENİ ŞAKRAN' },
	{ code: 778, name: 'YENİŞEHİR' },
	{ code: 779, name: 'YEŞİLYURT' },
]
