const districts = [
	{ eng: 'Adalar', district: 'Adalar' },
	{ eng: 'Arnavutkoy', district: 'Arnavutköy' },
	{ eng: 'Atasehir', district: 'Ataşehir' },
	{ eng: 'Avcilar', district: 'Avcılar' },
	{ eng: 'Bagcilar', district: 'Bağcılar' },
	{ eng: 'Bahcelievler', district: 'Bahçelievler' },
	{ eng: 'Bakirkoy', district: 'Bakırköy' },
	{ eng: 'Basaksehir', district: 'Başakşehir' },
	{ eng: 'Bayrampasa', district: 'Bayrampaşa' },
	{ eng: 'Besiktas', district: 'Beşiktaş' },
	{ eng: 'Beykoz', district: 'Beykoz' },
	{ eng: 'Beylikduzu', district: 'Beylikdüzü' },
	{ eng: 'Beyoglu', district: 'Beyoğlu' },
	{ eng: 'Buyukcekmece', district: 'Büyükçekmece' },
	{ eng: 'Catalca', district: 'Çatalca' },
	{ eng: 'Cekmekoy', district: 'Çekmeköy' },
	{ eng: 'Esenler', district: 'Esenler' },
	{ eng: 'Esenyurt', district: 'Esenyurt' },
	{ eng: 'Eyup', district: 'Eyüp' },
	{ eng: 'Fatih', district: 'Fatih' },
	{ eng: 'Gaziosmanpasa', district: 'Gaziosmanpaşa' },
	{ eng: 'Gungoren', district: 'Güngören' },
	{ eng: 'Kadikoy', district: 'Kadıköy' },
	{ eng: 'Kagithane', district: 'Kağıthane' },
	{ eng: 'Kartal', district: 'Kartal' },
	{ eng: 'Kucukcekmece', district: 'Küçükçekmece' },
	{ eng: 'Maltepe', district: 'Maltepe' },
	{ eng: 'Pendik', district: 'Pendik' },
	{ eng: 'Sancaktepe', district: 'Sancaktepe' },
	{ eng: 'Sariyer', district: 'Sarıyer' },
	{ eng: 'Silivri', district: 'Silivri' },
	{ eng: 'Sultanbeyli', district: 'Sultanbeyli' },
	{ eng: 'Sultangazi', district: 'Sultangazi' },
	{ eng: 'Sile', district: 'Şile' },
	{ eng: 'Sisli', district: 'Şişli' },
	{ eng: 'Tuzla', district: 'Tuzla' },
	{ eng: 'Umraniye', district: 'Ümraniye' },
	{ eng: 'Uskudar', district: 'Üsküdar' },
	{ eng: 'Zeytinburnu', district: 'Zeytinburnu' },
]

module.exports = { districts }
